version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6

jobs:
  build:
    docker:
      - image: circleci/node:latest 
    
    working_directory: ~/repo    
    steps:
      - checkout 

      - run: 
            name: install-dependencies
            command: npm install
      - run:
           name: create-env
           command: sh .circleci/scripts/create-env.sh      
      - run:
            name: run-tests 
            command: npm test 
      - run: make test-coverage
      - run:
            name: run-build
            command: npm run build